const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8080/api/v1.0";

export const apiEndpoints = {
    FETCH_FILES: `${BASE_URL}/files/my`,
    GET_CREDITS: `${BASE_URL}/users/credits`,
    TOGGLE_FILE: (id) => `${BASE_URL}/files/${id}/toggle-public`,
    DOWNLOAD_FILE: (id) => `${BASE_URL}/files/download/${id}`,
    DELETE_FILE: (id) => `${BASE_URL}/files/${id}`,
    UPLOAD_FILE: `${BASE_URL}/files/upload`,
    GET_CURRENT_USER: `${BASE_URL}/users/me`,
    UPDATE_PROFILE: `${BASE_URL}/users/me`,
    SET_PASSWORD: `${BASE_URL}/users/me/password`,
    DELETE_ACCOUNT: `${BASE_URL}/users/me`,
    LIST_SESSIONS: `${BASE_URL}/users/sessions`,
    REVOKE_OTHER_SESSIONS: `${BASE_URL}/users/sessions/others`,
    REVOKE_SESSION: (id) => `${BASE_URL}/users/sessions/${id}`,
    CREATE_ORDER: `${BASE_URL}/payments/create-order`,
    TRANSACTIONS: `${BASE_URL}/transactions`,
    PUBLIC_FILE_VIEW: (fileId) => `${BASE_URL}/files/public/${fileId}`,
    COMPRESS_PDF: `${BASE_URL}/pdf/compress`,
    TRANSLATE_PDF: `${BASE_URL}/pdf/translate`,
    CONVERT_FROM_PDF: `${BASE_URL}/pdf/from-pdf`,
    CONVERT_TO_PDF: `${BASE_URL}/pdf/to-pdf`,
    GET_PDF_JOB: (id) => `${BASE_URL}/pdf/jobs/${id}`,
    LIST_PDF_JOBS: `${BASE_URL}/pdf/jobs`,
    DOWNLOAD_PDF_JOB_RESULT: (id) => `${BASE_URL}/pdf/jobs/${id}/download`,
}